"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowUp, ArrowUpRight, Battery, Check, ChevronDown, CloudRain, Code2, Droplets, Expand, FlaskConical, HelpCircle, Leaf, Lightbulb, LoaderCircle, Moon, Play, PlugZap, Radio, RotateCcw, Sparkles, Sun, Terminal, Trees, Trophy, Volume2, VolumeX, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { ACTION_NAMES, applyPlan, initialWorld, interpretDemo, LIGHTS, makePlan, PLACES, publicState, ROBOT_COLORS, type Interpretation, type Place, type Plan, type RobotId, type World } from "@/lib/world";

const suggestions=["Send Pip to the pond", "Make the garden cozy", "Send someone to water the plants", "Get everyone inside"];
const missions=[
  {title:"A little help in the garden",description:"Water the plants while Dot stays at the charging dock.",hint:"Send someone to water the plants, but leave the charging robot alone.",icon:Droplets},
  {title:"An evening glow",description:"Light the porch and garden, keeping the cabin dark.",hint:"Turn on all the lights except the cabin.",icon:Lightbulb},
  {title:"Home before the storm",description:"Bring all three friends back to the cabin.",hint:"Get everyone inside before the storm.",icon:CloudRain},
];
type Entry={id:number;command:string;mode:"demo"|"live"};
export default function Home(){
  const [world,setWorld]=useState<World>(initialWorld), [command,setCommand]=useState("");
  const [mode,setMode]=useState<"demo"|"live">("demo"), [apiKey,setApiKey]=useState(""), [keyDraft,setKeyDraft]=useState("");
  const [connectionOpen,setConnectionOpen]=useState(false), [helpOpen,setHelpOpen]=useState(false), [busy,setBusy]=useState(false);
  const [moving,setMoving]=useState<RobotId[]>([]), [selected,setSelected]=useState<RobotId|null>(null);
  const [result,setResult]=useState<Interpretation|null>(null), [lastCommand,setLastCommand]=useState(""), [pending,setPending]=useState<Plan|null>(null);
  const [error,setError]=useState(""), [notice,setNotice]=useState("Your island is waiting. Tell your little crew what to do.");
  const [history,setHistory]=useState<Entry[]>([]), [mission,setMission]=useState(0), [achieved,setAchieved]=useState<number[]>([]);
  const [sound,setSound]=useState(false), [tab,setTab]=useState("island"), [showLabels,setShowLabels]=useState(true);
  const inputRef=useRef<HTMLInputElement>(null), abortRef=useRef<AbortController|null>(null), moveTimer=useRef<ReturnType<typeof setTimeout>|null>(null), audioRef=useRef<AudioContext|null>(null), requestSerial=useRef(0), sceneRef=useRef<HTMLDivElement>(null);
  const locked=busy||moving.length>0;
  useEffect(()=>()=>{abortRef.current?.abort();if(moveTimer.current)clearTimeout(moveTimer.current);audioRef.current?.close();},[]);
  useEffect(()=>{const t=setInterval(()=>setWorld(w=>({...w,robots:w.robots.map(r=>r.status==="charging"?{...r,battery:Math.min(100,r.battery+1)}:r)})),5000);return()=>clearInterval(t);},[]);
  function chime(){if(!sound)return;try{const a=audioRef.current??new AudioContext();audioRef.current=a;void a.resume();[523,659,784].forEach((f,i)=>{const o=a.createOscillator(),g=a.createGain();o.type="sine";o.frequency.value=f;g.gain.setValueAtTime(.001,a.currentTime+i*.08);g.gain.linearRampToValueAtTime(.06,a.currentTime+i*.08+.01);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+i*.08+.22);o.connect(g);g.connect(a.destination);o.start(a.currentTime+i*.08);o.stop(a.currentTime+i*.08+.25);});}catch{}}
  function runPlan(plan:Plan,answer:Interpretation,text:string){
    if(!plan.supported)return;const next=applyPlan(world,plan);setWorld(next);setPending(null);setNotice(plan.message);chime();
    setHistory(h=>[{id:Date.now(),command:text,mode:answer.mode},...h].slice(0,15));
    if(!plan.action.startsWith("lights")){setMoving(plan.robots);if(moveTimer.current)clearTimeout(moveTimer.current);moveTimer.current=setTimeout(()=>{setMoving([]);setWorld(w=>({...w,robots:w.robots.map(r=>r.status==="watering"?{...r,status:"idle"}:r)}));},1800);}
    const passed=mission===0?next.moisture>=60&&next.robots.find(r=>r.id==="dot")?.place==="charger":mission===1?next.lights.porch>0&&next.lights.garden>0&&next.lights.cabin===0:next.robots.every(r=>r.place==="cabin");
    if(passed)setAchieved(a=>a.includes(mission)?a:[...a,mission]);
  }
  async function submit(event?:React.FormEvent){
    event?.preventDefault();if(!command.trim()||locked)return;
    const text=command.trim(),serial=++requestSerial.current;setError("");setPending(null);setBusy(true);setLastCommand(text);
    try{let answer:Interpretation;
      if(mode==="demo")answer=interpretDemo(text,world);
      else{abortRef.current=new AbortController();const r=await fetch("/api/interpret",{method:"POST",headers:{"Content-Type":"application/json",...(apiKey?{"x-typesafe-key":apiKey}:{})},body:JSON.stringify(publicState(text,world)),signal:abortRef.current.signal});const data=await r.json() as Interpretation & {error?:string};if(!r.ok)throw new Error(data.error||"Jev could not interpret that command.");answer=data;}
      if(serial!==requestSerial.current)return;
      setResult(answer);const plan=makePlan(answer);
      if(!plan.supported){setNotice("No changes made. Try a single action with a named target.");setError(answer.mode==="demo"?"The demo understands the examples and simple variations. Connect Jev for broader language understanding.":"Jev could not resolve this command. Your island is unchanged. Review its action and target answers below, or rephrase the command.");setTab("interpretation");}
      else if(plan.needsReview){setPending(plan);setNotice("Let’s make sure I understood you.");setTab("interpretation");}
      else{runPlan(plan,answer,text);setCommand("");}
    }catch(e){if(serial===requestSerial.current&&!(e instanceof Error&&e.name==="AbortError"))setError(e instanceof Error?e.message:"Could not interpret the command.");}finally{if(serial===requestSerial.current)setBusy(false);}
  }
  function reset(nextMission?:number){requestSerial.current++;abortRef.current?.abort();if(moveTimer.current)clearTimeout(moveTimer.current);const fresh=initialWorld();if(nextMission===1)fresh.evening=true;if(nextMission===2)fresh.rain=true;setWorld(fresh);setMoving([]);setBusy(false);setResult(null);setPending(null);setError("");setCommand("");setSelected(null);setHistory([]);setNotice("A fresh start. Your little crew is ready.");if(nextMission!==undefined)setMission(nextMission);}
  function suggest(text:string){setCommand(text);setError("");inputRef.current?.focus();}
  const currentMission=missions[mission],MissionIcon=currentMission.icon,action=result?.answers.action,plan=result?makePlan(result):null;

  return <main className="tiny-app">
    <header className="topbar"><a className="brand" href="/" aria-label="Tiny World home"><span className="brand-mark"><Trees size={24}/></span><span>Tiny World<span className="brand-period">.</span></span></a><div className="top-note">A little world. In your words.</div><div className="top-actions"><button className={`connection-pill ${mode}`} onClick={()=>setConnectionOpen(true)}><Radio size={14}/>{mode==="live"?"Live Jev":"Demo mode"}<ChevronDown size={14}/></button><Button variant="ghost" size="icon" aria-label="How to play" onClick={()=>setHelpOpen(true)}><HelpCircle/></Button></div></header>
    <div className="game-grid"><section className="world-column" aria-label="Island playground">
      <div className="world-heading"><div><span className="island-dot"/>Fernwater island <span className="quiet">/ Sandbox</span></div><div className="world-tools"><Button size="icon" variant="ghost" title={sound?"Mute sound":"Enable sound"} aria-label={sound?"Mute sound":"Enable sound"} aria-pressed={sound} onClick={()=>setSound(!sound)}>{sound?<Volume2/>:<VolumeX/>}</Button><Button size="icon" variant="ghost" title="Reset island" aria-label="Reset island" onClick={()=>reset()}><RotateCcw/></Button><Button size="icon" variant="ghost" title="Full screen" aria-label="Expand island" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void sceneRef.current?.requestFullscreen().catch(()=>setNotice("Full screen isn’t available in this browser."));}}><Expand/></Button></div></div>
      <div ref={sceneRef} className={`scene ${world.evening?"evening":""} ${world.rain?"rainy":""}`}>
        <div className="scene-controls"><button onClick={()=>setWorld(w=>({...w,evening:!w.evening}))}>{world.evening?<Moon size={16}/>:<Sun size={16}/>} {world.evening?"Blue hour":"Afternoon"}<ChevronDown size={12}/></button><button aria-label={world.rain?"Clear the weather":"Start a storm"} aria-pressed={world.rain} onClick={()=>setWorld(w=>({...w,rain:!w.rain}))}><CloudRain size={16}/>{world.rain?"Storm":"Clear skies"}</button></div>
        <div className="scene-inner"><img className="island-art" src="/island.png" alt="A green island with a cabin, vegetable beds, a pond, and a dock connected by sandy paths" fetchPriority="high"/><div className="night-tint"/>
          {LIGHTS.map(l=><div key={l.id} className={`light-aura ${world.lights[l.id]>0?"on":""}`} style={{left:`${l.x}%`,top:`${l.y}%`,opacity:world.lights[l.id]}}/>)}
          {world.rain&&<div className="rain-overlay" aria-hidden="true">{Array.from({length:30},(_,i)=><i key={i} style={{left:`${(i*37)%100}%`,animationDelay:`${(i%7)*-.18}s`,animationDuration:`${.65+(i%3)*.15}s`}}/>)}</div>}
          {showLabels&&Object.entries(PLACES).map(([id,p])=><button key={id} className={`place-label place-${id}`} style={{left:`${p.x}%`,top:`${p.y+7}%`}} onClick={()=>suggest(`${selected?world.robots.find(r=>r.id===selected)?.name:"Pip"}, go to the ${p.name.toLowerCase()}`)} aria-label={`Prepare a command to go to the ${p.name.toLowerCase()}`}>{id==="charger"?<Zap size={11}/>:id==="garden"?<Leaf size={11}/>:null}{p.name}</button>)}
          {world.robots.map(r=><button key={r.id} className={`robot-token ${selected===r.id?"selected":""} ${moving.includes(r.id)?"moving":""} ${r.status==="resting"?"sleeping":""}`} style={{left:`${r.x}%`,top:`${r.y}%`,"--robot-color":ROBOT_COLORS[r.id]} as React.CSSProperties} aria-label={`${r.name}, ${r.status}, ${r.battery}% battery. Select robot`} onClick={()=>{setSelected(r.id);setNotice(`${r.name} is ${r.status} at the ${PLACES[r.place].name.toLowerCase()}.`);}}><span className="robot-state">{r.status==="charging"?<Zap size={14}/>:r.status==="resting"?"z z z":r.status==="watering"?<Droplets size={14}/>:null}</span><img src="/robot.png" alt="" draggable={false}/><span className="robot-name">{r.name}</span></button>)}
          {world.moisture>=60&&<div className="garden-watered"><Droplets size={15}/><span>Happy plants</span></div>}
        </div><div className="scene-bottom"><span><span className="live-dot"/>3 little lives, one little island</span><button onClick={()=>setShowLabels(!showLabels)}>{showLabels?"Hide labels":"Show labels"}</button></div>
      </div>
      <section className="command-desk" aria-label="Command your world"><div className="command-label"><Sparkles size={17}/><label htmlFor="world-command">What should happen next?</label><span>{mode==="demo"?"Local demo rules":"Powered by Jev"}</span></div><form className="command-form" onSubmit={submit}><Input id="world-command" ref={inputRef} value={command} onChange={e=>setCommand(e.target.value)} maxLength={500} placeholder="Tell your world what to do…" autoComplete="off" disabled={busy}/><Button type="submit" className="send-command" disabled={!command.trim()||locked} aria-label="Run command">{busy?<LoaderCircle className="spin" size={20}/>:<ArrowUp size={20}/>}</Button></form><div className="suggestions">{suggestions.map((s,i)=><button disabled={locked} key={s} onClick={()=>suggest(s)}>{i===0?<ArrowUpRight size={13}/>:i===1?<Lightbulb size={13}/>:i===2?<Droplets size={13}/>:<Trees size={13}/>} {s}</button>)}</div><div role="status" className={`command-feedback ${error?"error":""}`}>{busy?<><LoaderCircle className="spin" size={14}/>Jev is reading your command and island state…</>:error?<><HelpCircle size={14}/>{error}</>:<><Check size={14}/>{notice}</>}</div></section>
      <div className="crew-strip">{world.robots.map(r=><button key={r.id} onClick={()=>{setSelected(r.id);suggest(`${r.name}, `);}} className={`crew-card ${selected===r.id?"active":""}`}><span className="crew-portrait" style={{background:ROBOT_COLORS[r.id]}}><img src="/robot.png" alt=""/></span><span className="crew-copy"><strong>{r.name}</strong><span>{moving.includes(r.id)?"On the way":r.status==="charging"?"Recharging":r.status==="resting"?"Taking a nap":r.status==="watering"?"Watering plants":"Ready to help"}</span></span><span className="battery-label"><Battery size={16}/>{r.battery}%</span></button>)}</div>
    </section>
    <aside className="side-panel"><Tabs value={tab} onValueChange={setTab} className="main-tabs"><TabsList variant="line" className="side-tabs"><TabsTrigger value="island"><Trees size={16}/>Your island</TabsTrigger><TabsTrigger value="interpretation"><FlaskConical size={16}/>Interpretation{result&&<span className="new-result"/>}</TabsTrigger></TabsList>
      <TabsContent value="island" className="island-tab"><div className="mission-section"><div className="section-label"><span><Trophy size={16}/>Little missions</span><span>{achieved.length} / 3</span></div><div className="mission-icon"><MissionIcon size={26}/></div><h1>{currentMission.title}</h1><p>{currentMission.description}</p><button className="hint-button" onClick={()=>suggest(currentMission.hint)}><Play size={13}/>Try a command</button><div className="mission-progress">{missions.map((m,i)=><button key={m.title} className={`${mission===i?"current":""} ${achieved.includes(i)?"complete":""}`} aria-label={`Start mission ${i+1}: ${m.title}`} aria-pressed={mission===i} disabled={locked} onClick={()=>reset(i)}>{achieved.includes(i)?<Check size={13}/>:i+1}</button>)}</div>{achieved.includes(mission)&&<div className="mission-complete"><Trophy size={16}/>Mission complete. Nicely done!</div>}</div>
      <div className="island-status"><div className="section-label"><span>Island at a glance</span><Leaf size={15}/></div><div className="moisture-row"><span><Droplets size={16}/>Garden moisture</span><strong>{world.moisture}%</strong></div><div className="moisture-track"><i style={{width:`${world.moisture}%`}}/></div><p>{world.moisture<60?"The plants could use a drink.":"Freshly watered and looking good."}</p><div className="light-status">{LIGHTS.map(l=><div key={l.id}><Lightbulb size={16} className={world.lights[l.id]>0?"lit":""}/><span>{l.name}</span><span>{world.lights[l.id]>0?"On":"Off"}</span></div>)}</div></div><div className="field-note"><Sparkles size={18}/><div><strong>Small words. Real changes.</strong><p>Try “everyone,” name a friend, or leave someone out with “except.”</p></div></div></TabsContent>
      <TabsContent value="interpretation" className="interpretation-tab">{!result?<div className="empty-interpretation"><FlaskConical size={30}/><h2>Peek behind the magic.</h2><p>Run a command to see the selected action, targets, and uncertainty.</p><span>These are decisions, not a generated explanation.</span></div>:<>
        <div className={`result-mode ${result.mode}`}><span>{result.mode==="live"?<Radio size={14}/>:<Code2 size={14}/>} {result.mode==="live"?result.model:"Rule-based demo"}</span><span>{result.latency} ms</span></div>{result.mode==="demo"&&<p className="demo-disclaimer">Deterministic rule matches, not Jev probabilities. Connect Jev to explore model uncertainty.</p>}<blockquote>“{lastCommand}”</blockquote><div className="section-label"><span>{result.mode==="live"?"Action probabilities":"Matched action"}</span><span>Choice</span></div>
        {action?.type==="choice"&&<div className="probabilities">{Object.entries(action.probabilities).filter(([id,p])=>id!=="unknown"||p>0).sort((a,b)=>b[1]-a[1]).map(([id,p])=><div key={id} className={`probability ${action.choice===id?"winner":""}`}><div><span>{ACTION_NAMES[id as keyof typeof ACTION_NAMES]??id}</span><strong>{Math.round(p*100)}%</strong></div><div className="probability-track"><i style={{width:`${p*100}%`}}/></div></div>)}</div>}
        {action?.type==="choice"&&result.mode==="live"&&<p className="confidence-note">Distribution confidence <strong>{action.confidence.toFixed(2)}</strong><span>Not a guarantee of correctness.</span></p>}<div className="section-label"><span>Selected targets</span><span>Noul</span></div><div className="target-results">{Object.entries(result.answers).filter(([k])=>plan?.action==="unknown" ? k.startsWith("light_")||k.startsWith("robot_") : k.startsWith(plan?.action.startsWith("lights")?"light_":"robot_")).map(([k,a])=><div key={k} className={a.type==="noul"&&a.noul>.5?"chosen":""}><span>{k.startsWith("light_")?`${k.replace("light_","")} light`:k.replace("robot_","")}</span><strong>{a.type==="noul"?`${Math.round(a.noul*100)}%`:"—"}</strong></div>)}</div>
        {pending?<div className="review-plan"><strong>{pending.reviewReason?"Review an alternative":"One thing to check"}</strong>{pending.reviewReason&&<p>{pending.reviewReason}</p>}<p>{pending.message}</p>{pending.action==="move"&&(!pending.destination||(result.answers.destination.type==="choice"&&result.answers.destination.confidence<.55))?<><p>Choose where to send them:</p><div className="destination-options">{Object.entries(PLACES).map(([id,p])=><Button key={id} variant="outline" size="sm" onClick={()=>{runPlan({...pending,destination:id as Place,needsReview:false,message:`Send ${pending.robots.join(", ")} to ${p.name.toLowerCase()}.`},result,lastCommand);setCommand("");}}>{p.name}</Button>)}</div></>:<Button onClick={()=>{runPlan({...pending,needsReview:false},result,lastCommand);setCommand("");}}>Run this plan</Button>}<button className="cancel-plan" onClick={()=>{setPending(null);setNotice("Plan cancelled. Your island is unchanged.");}}>Cancel</button></div>:<div className="decision-summary">{plan?.supported?<Check size={16}/>:<HelpCircle size={16}/>}{notice}</div>}
        <div className="result-metrics"><div><span>Input tokens</span><strong>{result.usage?.input_tokens.toLocaleString()??"—"}</strong></div><div><span>Estimated API cost</span><strong>{result.usage?`$${(result.usage.input_tokens*.042/1e6).toFixed(6)}`:result.mode==="demo"?"No API call":"Not reported"}</strong></div></div><details className="raw-details"><summary><Code2 size={14}/>Raw answers</summary><pre>{JSON.stringify(result.answers,null,2)}</pre></details>
      </>}</TabsContent></Tabs>
      <div className="recent-section"><div className="section-label"><span><Terminal size={15}/>Recent activity</span><span>{history.length}</span></div>{history.length?history.slice(0,3).map(h=><div className="history-entry" key={h.id}><span><Check size={13}/></span><div><p>{h.command}</p><small>{h.mode==="live"?"Jev":"Demo"} · Done</small></div></div>):<p className="empty-history">Your first command starts the story.</p>}</div><div className="panel-footer"><span>Built to play. Powered by decisions.</span><a href="https://docs.typesafe.ai/introduction" target="_blank" rel="noreferrer">Meet Jev <ArrowUpRight size={13}/></a></div>
    </aside></div>
    <footer className="app-footer"><span><Leaf size={13}/>Take your time. It’s a tiny world.</span><button onClick={()=>setConnectionOpen(true)}>{mode==="live"?"Manage Jev connection":"Connect Jev for natural-language play"}<ArrowUpRight size={13}/></button></footer>
    <Dialog open={connectionOpen} onOpenChange={v=>{setConnectionOpen(v);if(!v)setKeyDraft("");}}><DialogContent className="connection-dialog"><DialogHeader><span className="dialog-icon"><PlugZap size={26}/></span><DialogTitle>Let Jev meet your island.</DialogTitle><DialogDescription>The demo uses simple local rules. Connect TypeSafe for real semantic decisions and probability distributions.</DialogDescription></DialogHeader><div className="mode-row"><div><strong>Use live Jev</strong><p>Commands are sent to TypeSafe.</p></div><Switch aria-label="Use live Jev" checked={mode==="live"} disabled={locked} onCheckedChange={checked=>{if(checked){setMode("live");}else{setMode("demo");setApiKey("");}setPending(null);}}/></div><label htmlFor="api-key" className="key-label">TypeSafe API key</label><Input id="api-key" type="password" autoComplete="off" value={keyDraft} onChange={e=>setKeyDraft(e.target.value)} placeholder={apiKey?"A session key is connected":"Paste your key for this session"}/><p className="key-note">Kept only in this page’s memory. Sent through this app’s backend to TypeSafe; never saved to browser storage. Refreshing forgets it.</p><Button disabled={locked||!keyDraft.trim()} onClick={()=>{setApiKey(keyDraft.trim());setKeyDraft("");setMode("live");setPending(null);setError("");setConnectionOpen(false);setNotice("Your next command will use the live Jev API.");}}>Connect and play <ArrowUpRight size={16}/></Button><button className="server-key-button" disabled={locked} onClick={()=>{setMode("live");setPending(null);setConnectionOpen(false);setError("");setNotice("Your next command will use the backend’s configured TypeSafe key.");}}>Use a server-configured key</button><div className="dialog-bottom"><a href="https://console.typesafe.ai/keys" target="_blank" rel="noreferrer">Get a TypeSafe key <ArrowUpRight size={13}/></a><button disabled={locked} onClick={()=>{setApiKey("");setMode("demo");setPending(null);setConnectionOpen(false);setError("");}}>Continue in demo mode</button></div></DialogContent></Dialog>
    <Dialog open={helpOpen} onOpenChange={setHelpOpen}><DialogContent className="help-dialog"><DialogHeader><DialogTitle>A few words go a long way.</DialogTitle><DialogDescription>Give one instruction at a time. Your crew can move, water plants, rest, and change the island’s lights.</DialogDescription></DialogHeader><ul><li><strong>Name a friend.</strong> “Send Moss to the pond.”</li><li><strong>Include everyone.</strong> “Get everyone inside.”</li><li><strong>Make an exception.</strong> “Turn on all lights except the cabin.”</li><li><strong>Let someone help.</strong> “Send someone to water the garden.”</li></ul><p>Click a robot to select it, or a place to prepare a command. The sun and cloud controls change the scene. Missions reset the island so each challenge starts fresh.</p><p>The Interpretation tab shows decisions and targets. Uncertain live commands pause for your review. Arithmetic and world changes happen in code.</p><Button onClick={()=>setHelpOpen(false)}>Let’s play</Button></DialogContent></Dialog>
  </main>;
}
